### ISSUE TITLE
[fix] Create getting method to response on server

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#105]
## 설명
애플리케이션을 키거나 주소창에서 접근할 때 브라우저는 url에 해당하는 데이터를 서버에 요청하는데, 서버에는 그 요청을 응답하는 코드가 존재하지 않으므로 구현이 필요함.

## 할일
- [ ] 서버에 root directory의 정적 파일인 Index.html을 전달하는 get 메서드를 생성

## 참조
- [Single Page Application & Routing](https://poiemaweb.com/js-spa)

**Comment by NamgungJongMin** [comment]
Roger
