### ISSUE TITLE
[feat] Create fake-data about user infomation

### ISSUE THREAD

**Issue by NamgungJongMin** [connectTo2/SweetMe#11]
## 설명
로그인 / 단어장 유저 정보 fetch를 위한 목데이터 3개 추가

## 할일
- [ ] ``` const state = {
  userInfo: {
    email: string,
    name: string,
    password: string,
    voca: [
      {
        vocaId: string(index-title),
        title: string,
        description: string,
        words: [
          { wordId: string(날짜-index), 단어: string, 뜻: string },
        ],
      },
    ],
    vocaCount: 0,
  },
};```

**Comment by parkseonup** [comment]
Mock data에 어떤 내용을 작성하실 건지 적어주세요~

**Comment by parkseonup** [comment]
종민님 설명에 작성해주신 내용들, 할일로 작성해주세요~

**Comment by NamgungJongMin** [comment]
수정했습니다.

**Comment by parkseonup** [comment]
네! 진행해주세요~
