### ISSUE TITLE
[refactor] Refactor VocaList Page render

### ISSUE THREAD

**Issue by jaerinjaerin** [connectTo2/SweetMe#113]
## 설명
- VocaList 페이지가 렌더링 될 때 서버에서 받아오는 정보 수정 (현재 undefined)
- 모달 팝업이 컴포넌트로서 동작하지 않는다고 생각하기 때문에 컴포넌트로 만들었던 인스턴스를 제거하고 VocaList 페이지 내에서 DOMString으로 생성

## 할일
- [ ] get 요청이 왔을 때 서버에서 확인하는 데이터 형식 확인
- [ ] res.send는 객체형식으로 보낸다. 
- [ ] client에선 받은 객체를 가지고 render할 때 prop으로 전달한다.

**Comment by parkseonup** [comment]
확인했습니다.
