### ISSUE TITLE
[fix] Set proxy config & server.js

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#114]
## 설명
vite.config.js에서 proxy 설정 변경에 따른 server 수정

## 할일
- [ ] rest api 통신으로 이뤄지는 요청은 /api를 붙여서 요청/응답한다.
- [ ] proxy를 root path로 하고, 모든 서버를 http://localhost:8000으로 전환한다.

**Comment by NamgungJongMin** [comment]
확인했습니다.
