### ISSUE TITLE
[feat] Add button to close toaster

### ISSUE THREAD

**Issue by NamgungJongMin** [connectTo2/SweetMe#116]
## 설명
생성된 토스터를 유저가 제거할 수 있는 버튼을 추가

## 할일
- [ ] 동적 생성할 토스트에 닫기 버튼 추가
- [ ] 토스터를 제거하는 addEventListener 메서드 추가

**Comment by parkseonup** [comment]
넹

**Comment by jaerinjaerin** [comment]
확인했습니다
