### ISSUE TITLE
[conf] Set folder tree

### ISSUE THREAD

**Issue by jaerinjaerin** [connectTo2/SweetMe#12]
## 설명
파일 구조 세팅하기

## 할일
- [ ] 파일 구조는 다음과 같습니다. 
- [ ] core 👉🏻 Component.js
- [ ] component 👉🏻 Nav / SignIn / SignUp / VocaList / VocaItem / User / WordList / WordItem / Game.js
- [ ] dom 👉🏻 index / render / eventHolder / diff.js
- [ ] page 👉🏻 signin / signup / vocalist / wordlist / game

**Comment by parkseonup** [comment]
시작해주세요!
