### ISSUE TITLE
[feat] Change timing for saving userInfo in server

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#120]
## 설명
signin에서 post 요청시 전달받은 email, password로 서버의 userInfo를 저장하는 시점을 토큰이 발급된 유효성 검사할 때(auth)로 변경

## 할일
- [ ] auth 함수의 try문 안에서 토큰이 디코딩된 페이로드로 userInfo를 불러와서 server.js의 전역에 변수로 저장

**Comment by parkseonup** [comment]
가입 회원을 검색하지 못하는 버그가 있습니다. 해결하고 재업 하겠습니다.

**Comment by jaerinjaerin** [comment]
확인했습니다
