### ISSUE TITLE
[conf] Add scripts to rm -rf back/dist/ in package.json

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#122]
## 설명
현재 설정된 package.json의 mv-dist는 back 폴더에 dist가 없을 경우에는 front/dist를 back 폴더로 그대로 옮겨주지만, back 폴더 내에 dist가 있을 경우에는 dist 안에 dist로 옮기기 때문에 기대하는 구조가 아니게 된다. 때문에 back에 있는 dist를 지울 수 있도록 script를 추가해주었다.

## 할일
- [ ] script에 rm-dist 추가: `"rm-dist": "rm -rf back/dist/"`
- [ ] script의 start에 rm-dist 추가: `"start": "run-s front-build rm-dist mv-dist back-start"`

**Comment by jaerinjaerin** [comment]
확인했습니다:)
