### ISSUE TITLE
[fix] Change logic for getting userInfo in server

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#123]
## 설명
현재 서버에서 전역에 변수로 userInfo를 저장하는 로직은 여러명이 애플리케이션에 접근했을 경우 정상적으로 동작하지 않으므로, 서버에 변수로 저장하지 않고 브라우저로 바로 전달할 수 있도록 변경한다.

## 할일
- [ ] getUserInfo 라는 함수를 사용하여 userInfo가 필요한 페이지마다 브라우저에 바로 전달해준다.

**Comment by jaerinjaerin** [comment]
확인했습니다
