### ISSUE TITLE
[Feat] Create a super component

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#16]
## 설명
컴포넌트들의 Super(상위) 컴포넌트 생성 (./core/Component.js)

## 할일
- [ ] class로 컴포넌트들의 상위 컴포넌트인 Component 생성
- [ ] Component는 props를 받도록 함
- [ ] 이벤트가 중복 등록되지 않도록 체크하는 holdEvents 메서드 생성
  - holdEvents 메서드는 자식 클래스가 가지고 있을 필요가 없으므로 private으로 만듦 
- [ ] Component가 호출되면 holdEvents 메서드가 호출되도록 constructor에 호출문 작성
- [ ] state를 변경하고 render 함수를 호출하는 setState 메서드 생성
  - 자식 컴포넌트들이 state를 변경해야 하기 때문에 prototype 메서드로 등록 (public)
- [ ] render 메서드 생성
  - render 메서드는 추상 메서드(오버라이딩되어야 호출되는 메서드)로 구현
  - Component의 render는 자식 컴포넌트가 render 메서드를 가지고 있지 않다는 에러를 띄우기 위한 목적으로 사용됨. (컴포넌트들을 props 방식으로 만들고 있기 때문에, 자식 컴포넌트들은 모두 render 메서드를 가져야 함)
- [ ] dom 폴더의 eventHolder 배열과 render 함수를 export 받음
  - holdEvent 메서드에서 eventHolder 배열을 확인함
  - setState 메서드에서 render 함수를 호출함

**Comment by jaerinjaerin** [comment]
확인했습니다:)
