### ISSUE TITLE
[Feat] Create rendering function && binding eventHandler function in render.js

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#17]
## 설명
실제 DOM에 rendering을 일으키는 render 함수와 eventHolder 배열에 담긴 정보로 이벤트 핸들러를 등록하는 bindEventHandler 함수 구현

## 할일
- [ ] render 함수는 render 메서드 호출시 domString을 반환하는 최상위 컴포넌트(RootComponent)와 렌더링될 $container를 인수로 받음
- [ ] render 함수 외부에 리렌더링시 RootComponent의 재호출이 일어나지 않고, 초기 렌더링시 전달받은 RootComponent의 instance(이하 instance)와 $container를 기억하기 위한 변수 생성
- [ ] diff 알고리즘을 통해 상태가 변경된 것만 렌더링될 수 있도록 $container와 instance의 render 메서드가 반환한 domString을 diff 함수의 인수로 전달함
  - dom 폴더의 diff.js를 import 함
- [ ] 렌더링이 일어나면 이벤트 핸들러가 등록될 수 있도록 bindEventHandler 함수를 호출함 
- [ ] bindEventHandler는 eventHolder 배열을 순회하면서 addEventListener 메서드를 통해 이벤트 핸들러를 등록함
  - eventHolder 배열의 요소: `{type: 이벤트의 타입, selector: 이벤트 호출자, handler: 이벤트 핸들러}`

## 참조
- #16

**Comment by jaerinjaerin** [comment]
확인했습니다:)
