### ISSUE TITLE
[Feat] Create diff.js process

### ISSUE THREAD

**Issue by jaerinjaerin** [connectTo2/SweetMe#18]
## 설명
diff 알고리즘을 적용한 효율적인 렌더링(Reconciliation)을 위해 diff.js 로직 구현

## 할일
- [ ] RealDOM과 Virtual DOM 비교를 진행한다. 
- [ ] 엘리먼트 타입이 다른 경우 DOM을 교체한다.
- [ ] 엘리먼트 타입이 같은 경우 동일한 내용은 유지하고 변경된 atrribute만 교체한다.
- [ ] 자식요소가 있다면 재귀적 처리를 통해 자식요소까지 동일한 처리를 반복한다. 
- [ ] 기존 노드와 가상 노드가 모두 텍스트 노드인데 textContent가 다르면 새로운 textContent로 교체한다.
- [ ] 기존 node 또는 새로운 node가 comment node면 무시한다.

## 참조
- [리액트 재조정](https://ko.reactjs.org/docs/reconciliation.html)
- [Virtual DOM](https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Virtual-DOM/#_1-%E1%84%80%E1%85%A1%E1%84%89%E1%85%A1%E1%86%BC%E1%84%83%E1%85%A9%E1%86%B7-virtualdom-%E1%84%86%E1%85%A1%E1%86%AB%E1%84%83%E1%85%B3%E1%86%AF%E1%84%80%E1%85%B5)

**Comment by parkseonup** [comment]
텍스트 노드도 비교해주셔야 합니다! (주석, text)

**Comment by jaerinjaerin** [comment]
텍스트 노드 비교 과정 추가하였습니다.

**Comment by parkseonup** [comment]
진행해주세요~
