### ISSUE TITLE
[feat] Add auth function for authorizing user

### ISSUE THREAD

**Issue by NamgungJongMin** [connectTo2/SweetMe#2]
## 설명
JWT 토큰 발행을 위한 auth 작성.
사용자기 요청한 정보를 담아서 암호화된 토큰 생성(AccessToken + RefreshToken)

## 할일
- [x] 사용자에게 email과 password를 전달받아 user.js에서 유저가 등록되어있는지를 필터하여 userInfo에 저장
- [x] 유저가 등록되어있다면 AccessToken과 RefreshToken을 발급
- [x] 발급한 토큰을 쿠키, 정상 발급 확인 메시지 respense 객체에 전달
- [x] 발급이 실패한 경우 에러처리

**Comment by parkseonup** [comment]
설명이 빠졌습니다. 작성해주세요~

**Comment by NamgungJongMin** [comment]
수정했습니다.

**Comment by parkseonup** [comment]
진행해주세요~
