### ISSUE TITLE
[conf] Add .env & Edit .gitignore

### ISSUE THREAD

**Issue by NamgungJongMin** [connectTo2/SweetMe#20]
## 설명
.env파일 전역에 생성 및 .gitignore 수정

## 할일
- [x] .env파일 전역에 생성 
- [x] .gitignore 파일 .env관련 코드 삭제.

**Comment by parkseonup** [comment]
참조 링크 없으면 지워주세요!

**Comment by parkseonup** [comment]
진행해주세요~
