### ISSUE TITLE
[feat] Add route for auth in server

### ISSUE THREAD

**Issue by NamgungJongMin** [connectTo2/SweetMe#3]
## 설명
signin/ signup에서 받아온 input 정보에 대해 서버에서 처리할 함수를 작성.

## 할일
- [ ] get
- [ ] post
- [ ] 에러처리
- [ ] 토큰 생성
- [ ] 쿠키에 토큰 설정

**Comment by parkseonup** [comment]
진행해주세요~

**Comment by NamgungJongMin** [comment]
현재 디렉토리 구조와 맞지 않는 이슈입니다. 지워주세요.
