### ISSUE TITLE
[Feat] Create entry point of all pages (App.js)

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#33]
## 설명
모든 페이지의 진입점인 App.js 구현
(state를 변경하는 함수들은 각 컴포넌트가 구현될 때 따로 추가할 예정)

## 할일
- [ ] 서버에서 user 정보 받아오는 fetchData 메서드 생성 -> 받아온 user 정보를 state 프로퍼티에 저장
- [ ] routes 객체 생성 `const routes = [{ path: 경로, page: 페이지 }]`
- [ ] 현재 path를 확인해서 routes 객체에 담긴 컴포넌트의 render 메서드를 호출하고, 반환받은 domString을 모아서 반환하는 render 함수 생성

**Comment by jaerinjaerin** [comment]
확인했습니다. :) 
fetch는 데이터를 받아오는 거니까 fetchData는 어떨까요?

**Comment by parkseonup** [comment]
넵 수정했습니다
