### ISSUE TITLE
[Feat] Create VocaItem HTML & style.css

### ISSUE THREAD

**Issue by jaerinjaerin** [connectTo2/SweetMe#35]
## 설명
VocaItem 렌더함수가 호출될 때 return HTML DomString 구현
VocaItem component css 생성

## 할일
- [ ] component > VocaList.js render함수 내에 DomString을 return한다. 
- [ ] VocaItem은 li로 구성한다. 
- [ ] li 안에는 h3, p, button으로 구성한다. (단어장 이름, 설명, 삭제버튼)
- [ ] className은 다음과 같다. 
- [ ] li: voca-item
- [ ] h3: title
- [ ] p: description
- [ ] button: delete

**Comment by parkseonup** [comment]
확인했습니다.
