### ISSUE TITLE
[Fix] Rename page files

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#37]
## 설명
page 폴더에 있는 파일명 변경

## 할일
- [ ] signin.js -> SignInPage.js
- [ ] signup.js -> SignUpPage.js
- [ ] game.js -> GamePage.js
- [ ] vocalist.js -> VocaListPage.js
- [ ] wordlist.js -> WordListPage.js

**Comment by jaerinjaerin** [comment]
네 확인했습니다
