### ISSUE TITLE
[feat] Add route for page using userInfo in server

### ISSUE THREAD

**Issue by NamgungJongMin** [connectTo2/SweetMe#4]
## 설명
각 페이지에서 사용할 userInfo에 대한 라우터 구현

## 할일
- [ ] get
- [ ] post
- [ ] patch
- [ ] delete

**Comment by parkseonup** [comment]
route 코드가 어떤걸 말씀하시는걸까요?

**Comment by parkseonup** [comment]
할일 checkbox로 작성해주세요~ dot list로 바뀌었습니다!

**Comment by NamgungJongMin** [comment]
수정했습니다.

**Comment by parkseonup** [comment]
진행주세요!

**Comment by NamgungJongMin** [comment]
현재 디렉토리 구조와 맞지 않는 이슈입니다. 지워주세요.
