### ISSUE TITLE
[feat] Create responding to the get('/user') method

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#42]
## 설명
App.js의 fetchData 메서드를 호출 할 때 axios.get('/user')로 요청되는 userInfo data를 서버에서 client로 전달함.

## 할일
- [ ] axios.get('/user') 메서드가 요청될 때 client에 userInfo의 data를 보냄

**Comment by NamgungJongMin** [comment]
확인했습니다.
