### ISSUE TITLE
[feat] Create VocaList component HTML & CSS

### ISSUE THREAD

**Issue by jaerinjaerin** [connectTo2/SweetMe#44]
## 설명
VocaList component가 렌더링될 때 반환할 DOMString 구현 및 CSS 파일 생성

## 할일
- [ ] VocaList는 ul로 구성한다. 
- [ ] ul 안의 li 요소들은 VocaItem 컴포넌트를 불러온다. 
- [ ] DOMString 마지막 요소에 +button 요소를 추가한다. (+ 버튼은 항상 마지막에 렌더링되어야한다.)

**Comment by parkseonup** [comment]
확인했습니다.

**Comment by jaerinjaerin** [comment]
+버튼 HTML 요소가 누락되었습니다.  추가 후 다시 요청하겠습니다. 😢
