### ISSUE TITLE
[feat] Create getUserData function

### ISSUE THREAD

**Issue by NamgungJongMin** [connectTo2/SweetMe#50]
## 설명
클라이언트에서 서버로 요청할 때 클라이언트가 토큰을 가지고 있을 경우 userData를 반환하는 함수를 작성

## 할일
- [ ] 클라이언트로부터의 get요청의 Headers에 authorization을 검증하여 토큰을 확인하고
- [ ] 토큰이 있으면 user 정보를 return하고, 없으면 500 status를 반환하는 함수 작성.

**Comment by parkseonup** [comment]
진행해주세요~
