### ISSUE TITLE
[feat] Create each route & Creat handler function

### ISSUE THREAD

**Issue by NamgungJongMin** [connectTo2/SweetMe#52]
## 설명
클라이언트에서의 axios 요청을 처리할 각각의 라우터 작성. 
각각에 라우터에 콜백함수로 전달할 handler 함수 템플릿 작성.

## 할일
- [ ] /vocalist : get, post, delete
- [ ] /wordlist : get, post, patch, delete
- [ ] /game : get
- [ ] /signup : post
- [ ] /logout : get
- [ ] 폴더구조 변경 / 기존 작성한 signin 라우터 정리.

**Comment by parkseonup** [comment]
확인했습니다~
