### ISSUE TITLE
[fix] Connect Vite server with express server

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#56]
## 설명
Vite server(client)와 express server(server)가 통신하지 않는 문제 해결

## 할일
- [ ] vite.config.js 내 server proxy 수정
- [ ] vite.config.js 내 server, privew port 설정
- [ ] vite.config.js 내 vite 최신 문법 컴파일 하는 설정 추가
- [ ] express server에서 CORS 임시 해결

**Comment by jaerinjaerin** [comment]
확인했습니다
