### ISSUE TITLE
[feat] Build css structure

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#58]
## 설명
css 구조를 설계하고 적용.
필요없는 template 파일 삭제

## 할일
- [ ] common.module.css 생성
- [ ] base.css 생성
- [ ] style.css 파일명 normalize.css로 변경
- [ ] font-family 적용
- [ ] 기존 vite template 파일 삭제

**Comment by jaerinjaerin** [comment]
네 확인했습니다:)

**Comment by NamgungJongMin** [comment]
확인했습니다.
