### ISSUE TITLE
[feat] Add Toaster component

### ISSUE THREAD

**Issue by NamgungJongMin** [connectTo2/SweetMe#6]
## 설명
signup 버튼 클릭 후 JWT 토큰의 서명이 유효할 때 회원가입이 완료되었음을 알리는 toaster 구현.

## 할일
- [ ] 사용자에게 Type, Title, Text를 전달받아 해당 내용을 toaster 내에 표시.
- [ ] toaster는 1초 뒤 자동으로 사라짐.

**Comment by parkseonup** [comment]
toaster 기능에 어떤게 있나요?

**Comment by NamgungJongMin** [comment]
수정했습니다.

**Comment by parkseonup** [comment]
signin 페이지에도 toaster가 필요한가요? 
signup 페이지가 아닐까요?

할일에 toaster 기능을 상세하게 추가해주면 좋을 것 같습니다.
(예시: 생성된 토스트는 3초 후 자동 삭제)

**Comment by NamgungJongMin** [comment]
수정했습니다.

**Comment by parkseonup** [comment]
진행해주세요!

**Comment by NamgungJongMin** [comment]
toaster 시작하겠습니다. inprogress 달아주세용

**Comment by parkseonup** [comment]
signin에서 submit 됐을 때 user인지 확인하고, 없으면 가입된 정보가 없다고 toaster를 띄워줘야 합니다.
toaster type에 failed와 success 두 가지로 만들어주세요!

- failed는 signin에서 사용
- success는 signup에서 사용

그리고 1초 후 자동삭제 되도록 만든다고 하셨는데, 사용자가 toaster 메시지를 커스텀할 수 있듯 시간을 커스텀할 수 있도록 만드는게 어떨까요?
failed 됐을때 1초는 시간이 너무 짧은 듯 합니다!
