### ISSUE TITLE
[fix] Solve the problem of not matching & finding routes 

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#70]
## 설명
App.js에서 routes 프로퍼티가 가진 path를 현재 path와 비교하지 못하는 문제 해결

## 할일
- [ ] routes 프로퍼티의 path 프로퍼티 값인 정규표현식 수정
- [ ] vocaId 변수 할당문에 작성된 match 메서드 수정

**Comment by NamgungJongMin** [comment]
확인했습니다.
