### ISSUE TITLE
[Bug] &#x27;/&#x27; route get 404 Error

### ISSUE THREAD

**Issue by jaerinjaerin** [connectTo2/SweetMe#77]
## 설명
- / 라우터로 접근했을 때, 404 에러를 발생시킵니다. 
- 각각의 path에 접근했을 때, 해당 라우터.js 파일로 넘어가는데 루트 서버로 접근했을 때 넘어갈 수 있는 모듈이 없습니다. 
- 라우터 path 수정이 필요합니다. 
- app.use('/', vocalist);로 변경 필요

## 파일 경로
- */server.js*

**Comment by parkseonup** [comment]
미팅 요청합니다...
