### ISSUE TITLE
[feat] Render vocaList if it exists

### ISSUE THREAD

**Issue by jaerinjaerin** [connectTo2/SweetMe#8]
## 설명
voca item이 존재하는 경우, voca item 렌더링하기

## 할일
- [ ] voca 페이지에 접근했을 때, 유저가 vaca list를 가지고 있는지 확인한다. (서버에 요청)
- [ ] 가지고 있다면 voca List를 렌더링한다. 
- [ ] 가지고 있지 않다면 +버튼 요소만 렌더링한다. 

## 참조
- [Route methods](https://expressjs.com/en/guide/routing.html)

**Comment by parkseonup** [comment]
진행해주세요

**Comment by jaerinjaerin** [comment]
해당 issue 지금 진행해도 될까요?
