### ISSUE TITLE
[feat] Create Routing

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#80]
## 설명
동적인 페이지 이동이 일어날 수 있도록 Routing 구현

## 할일
- [x] changePath 메서드 보강
- [x] pushState 메서드를 호출하면 주소창의 url을 변경시키도록 구현 (pjax)
- [ ] a태그를 클릭하면 a태그의 href 정보를 받아서 페이지 이동될 수 있도록 함
- [ ] 로그인이 완료된 상태가 아닐시 뒤로가기, 앞으로가기 버튼 클릭 방지
- [ ] 새로고침시 서버에서는 index.html을 전달하고, 클라이언트에서는 현재 pathname에 맞춰 페이지를 렌더링할 수 있도록 함

## 참조
- [Single Page Application & Routing](https://poiemaweb.com/js-spa)

**Comment by NamgungJongMin** [comment]
확인했습니다.

**Comment by jaerinjaerin** [comment]
확인했습니다.
