### ISSUE TITLE
[feat] Create modal popup when deleteButton clickevent occured

### ISSUE THREAD

**Issue by jaerinjaerin** [connectTo2/SweetMe#9]
## 설명
삭제버튼을 눌렀을 때 삭제 확인 modal 생성하기

### 구현은 다음과 같습니다. 
- [x] modal 요소는 처음에 비표시를 해야한다. 
- [ ] 삭제 버튼을 누르면 modal 요소를 표시한다. 
- [ ] 아니오를 누르면 다시 modal 요소를 비표시한다. 
- [ ] 예를 누르면 vocaId를 확인하고 서버에 DELTE/vocaId 메서드를 요청한다. 

### 
- [ ] 삭제버튼을 클릭할 때 삭제버튼 요소를 브라우저에서 확인할 수 있는 지 확인한다.(console.log(e.target))
- [ ] DOM 요소가 잘 들어오는지 확인이되면 이벤트 핸들러를 작성한다. 
- [ ] 이벤트 핸들러 내에서는 modal을 비표시하고 표시하는 클래스를 추가하고 삭제하는 로직을 구현한다.

**Comment by parkseonup** [comment]
참조 항목 비었습니다~ 참조할 링크가 없다면 지워주세요!

**Comment by jaerinjaerin** [comment]
네 알겠습니다 :)

**Comment by parkseonup** [comment]
진행해주세요!

**Comment by parkseonup** [comment]
Vocaitem 삭제 버튼 클릭시, 삭제 확인하는 모달창도 구현해주셔야 합니다~ 추가해주세요!

**Comment by jaerinjaerin** [comment]
issue 다시 작성했습니다!

**Comment by parkseonup** [comment]
진행해주세여~
