### ISSUE TITLE
[feat] Create Toaster's template

### ISSUE THREAD

**Issue by NamgungJongMin** [connectTo2/SweetMe#94]
## 설명
사용자가 Toaster 컴포넌트를 어떻게 사용할지에 대한 템플릿 작성.

## 할일
- [ ] 현재 Toaster가 띄워져있는지를 true false로 판별하는 Toaster state 작성
- [ ] 버튼 클릭시 true / 사용자가 지정한 시간 후에 false로 자동 변환

**Comment by parkseonup** [comment]
확인했습니다~
