### ISSUE TITLE
[feat] Routing when move pages from the login state

### ISSUE THREAD

**Issue by parkseonup** [connectTo2/SweetMe#95]
## 설명
로그인 상태에서 뒤로 가기 버튼이나 주소창의 url로 signin 페이지에 접근하려 할 때 다른 페이지로 전환하는 라우팅 구현

## 할일
- [ ] 뒤로 가기 버튼이나 주소창 url로 signin 페이지에 접근시 main 페이지로 라우팅

**Comment by jaerinjaerin** [comment]
확인했습니다

**Comment by NamgungJongMin** [comment]
확인했습니다.
