### ISSUE TITLE
[feat] Create User component & CSS

### ISSUE THREAD

**Issue by jaerinjaerin** [connectTo2/SweetMe#98]
## 설명
- vocaListPage 내에서 user component 생성 & CSS 구현

## 할일
- [ ] vocaList 페이지에서 user 데이터를 가져온다. (기능구현완료)
- [ ] 받아온 정보를 User Component에 전달한다. 
- [ ] User Component는 user name과 등록한 단어의 갯수를 보여준다.

**Comment by parkseonup** [comment]
확인했습니다
